### ISSUE TITLE
inline <img src="*.svg"> as svg

### ISSUE THREAD

**Issue by popeindustries** [popeindustries/inline-source#2]

**Comment by hanifbbz** [comment]
this would be really awesome. I need it so badly...

**Comment by popeindustries** [comment]
I have a working initial version of this, but I'm wondering what the expected behaviour should be. My initial thought would be to convert an `<img src="foo.svg" />` to an inline `<svg>` tag, but I realise that some might want a base64 `<img>` version instead (same as for other images). What do you think?

**Comment by popeindustries** [comment]
I've added a new option `svgAsImage` so you are able to inline as an `<img>` instead of the default `<svg>`

**Comment by hanifbbz** [comment]
what if the "inline" attribute could actually get some value?

For example `inline="base64"` would put a base64 encoded version of a SVG in the file while `inline="import"` would just copy paste the file content. For SVG the case is really interesting because it can also be imported as an object (it's not as disasterous as it sounds like). See: https://css-tricks.com/using-svg/

If you decide to accept a value for `inline`, maybe it can do some cool stuff for other types of inlining as well. For example it can import `sass` but actually convert it to CSS. This is something that is ideal for plugin writers. Anyway, without exploding the `inline-source` project into another webpack, I think you've done a great job and if it puts the SVG in the DOM, it'll cover at least my use case.

**Comment by popeindustries** [comment]
Take a look at custom handlers and props. With those you should be able to make your own svg object embed version rather easily, as well as the sass example:

```js
Inline('<link type="sass" inline src="File.sass">', {handlers:[
function (source, context, next) {
  if (source.fileContent
    && !source.content
    && (source.type == 'sass')) {
      source.content = sass.compile(source.fileContent);
      next();
  } else {
    next();
  }
};
]}, function (err, html) {
  //...
});

```
