### ISSUE TITLE
API changes + cache

### ISSUE THREAD

**Issue by tamtakoe** [popeindustries/inline-source#23]
It is good plugin, especially `sync` mode. But this API is not comfortable

1) I need to set `htmlpath` and `rootpath`. `rootpath` is `process.cwd()` by default.
Generally resources defined relative to the directory with index file and index file called `index.html`. Then API will like
```js
var indexPath = 'project/index.html'

inline(indexPath, {//index.html path. Default: path.join(__dirname, 'index.html')
    root: 'public' //default: path.dirname(indexPath).
});

//or

inline('project/index.html'); //will be work in most cases
```

2) It will be good to cache index file and resources
```html
//index.html
...
<script src="config.js" inline></script>
<script src="lib.js" inline></script>
<link href="lib.css" rel="stylesheet" inline>
...
```
I build several `index.html` with different configs
```js
projects.forEach(function(project) {
    var html = inline('project/index.html', {
        cache: { //index.html and resources put to cache
            'config.js': project.config //I change content in cache
        }
    });
    ...
})
```

3) It will be good to use content instead of index path
```html
//index.html
...
<script src="config.js" config></script>
<script src="lib.js" inline></script>
<link href="lib.css" rel="stylesheet" inline>
...
```
I build several `index.html` with different configs
```js
var baseIndex = inline('project/index.html');

projects.forEach(function(project) {
    var html = inline({
        content: baseIndex,
        attribute: 'config',
        cache: {
            'config.js': project.config
        }
    });
    ...
})
```

4) It will be good to use `attribute: undefined` by default for inlining all resources tags

5) It is more logical if `compress: false` by default

6) Add `exclude` for excluded resources (as in Karma config).
```js
inline('project/index.html', {
    exclude: ['config.js']
});
```

**Comment by popeindustries** [comment]
Thanks for your input. I'm not sure I follow all your suggestions, but I can address a few of them:

1) You can avoid relying on `rootpath` by using relative source paths for each resource. Alternatively, if you're writing you're own build script, you could `process.chdir(path.dirname(htmlpath))` before calling `inline`.

2) Caching is probably better handled outside of this module, but it's not difficult to manually break up into separate `parse` and `inline` steps. See [buddy/helpers/parse](https://github.com/popeindustries/buddy/blob/master/lib/helpers/parse.js#L26-32) and [buddy/helpers/inline](https://github.com/popeindustries/buddy/blob/master/lib/helpers/inline.js#L91-103)

3) Just pass in your html string instead of path to `inline`

4-5) I'm not sure I see the use case for inline all resources by default. This module is primarily used for generating production ready code, and not all resources are small enough to inline. For the same reason, compressed is desirable as the default.

6) There is an `ignore` property, but it currently only operates on `tag`, `type`, or `format`. It would be easy to also add a match on path as well.

**Comment by tamtakoe** [comment]
This is bad way to use global `process.chdir` for local changes ;)

A lot of plugins like inline source, minifiers, compilers etc. use `compress: false`/`uglifiJS: false`/`minifyCSS: false`/etc. by default. It is standart
