### ISSUE TITLE
Inline any tags 

### ISSUE THREAD

**Issue by cristim** [popeindustries/inline-source#48]
It should have an option to inline any tags, regardless if they contain the inline attribute or not.

**Comment by popeindustries** [comment]
I like that it's declarative, but I'm open to the idea. 

What do you think of ` { attribute: false }` or similar?

**Comment by Rozbo** [comment]
i want this too

**Comment by SMEmp** [comment]
Echoing this: I'm looking into this because of platform restrictions I have no control over.

Basically we can Base64 encode a single HTML page and upload that.  A plugin like this would help us to at least not have to mix everything into a single file upfront, but if any inlinable elements get missed, they simply won't appear in the final build.

If I could enforce this via the build tool itself rather than linting (and then trying to get people to care about the linter) that would be ideal.

**Comment by popeindustries** [comment]
@SMEmp is this the desired behaviour?:

1. parse all inlineable tags with or without `inline` attribute
2. resolve all inlineable sources
3. **remove** all tags that can't be resolved
4. inline resolved sources

**Comment by SMEmp** [comment]
If step 3 prints line/col to stdout then that works for me.

Non zero exit code whenever step 3 is reached would also be handy, but since mine is a unique use case I'm not dead set on that.

I appreciate the quick response and requirements gathering.  :+1:
